### ISSUE TITLE
People.get API returns Daily Limit error

### ISSUE THREAD

**Issue by PanosJee** [googleplus/gplus-quickstart-python#11]
I get the following error

```javascript
{
 "error": {
  "errors": [
   {
    "domain": "usageLimits",
    "reason": "dailyLimitExceededUnreg",
    "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup.",
    "extendedHelp": "https://code.google.com/apis/console"
   }
  ],
  "code": 403,
  "message": "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."
 }
}
```
when I am accessing the G+ People API as in this demo. I don't see how I am not authenticated because I use the OAuth 2.0 credentials to make the api call & I have turned on G+ API in my API console.

Any ideas?

**Comment by gguuss** [comment]
This happens when you have not configured the sample's `client_secrets.json` file with your own credentials from the developer console here: https://console.developers.google.com

Make sure that you have configured the project as described in the instructions:
https://developers.google.com/+/quickstart/python

**Comment by gguuss** [comment]
Closing - please reopen if the configured sample is not working.
